# Generated by Django 4.2.24 on 2025-09-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
